heat_template_version: 2017-02-24

parameters:
    image:
        type: string
        description: Image type for the web server
    
    flavor:
        type: string
        description: Flavor for the web server

    net1:
        type: string
        description: net1

    net2:
        type: string
        description: net2

    http_security_group:
        type: string
        description: Nombre del grupo de seguridad por acceso a http

    postgres_security_group:
        type: string
        description: Nombre del grupo de seguridad por acceso a PostgreSQL

    icmp_security_group:
        type: string
        description: Nombre del grupo de seguridad por acceso a icmp

    ssh_security_group:
        type: string
        description: Nombre del grupo de seguridad por acceso a ssh

resources:
    vm-web_net1_port:
        type: OS::Neutron::Port
        properties:
            network_id: { get_param: net1 }
            security_groups: 
                - { get_param: ssh_security_group }
                - { get_param: icmp_security_group }

    vm-web_net2_port:
        type: OS::Neutron::Port
        properties:
            network_id: { get_param: net2 }
            security_groups: 
                - { get_param: postgres_security_group }
                - { get_param: icmp_security_group }
    
    vm-web:
        type: OS::Nova::Server
        properties:
            image: { get_param: image }
            flavor:  { get_param: flavor }
            networks:
                - port: { get_resource: vm-web_net1_port }
                - port: { get_resource: vm-web_net2_port }
