heat_template_version: 2017-02-24

parameters:
    image:
        type: string
        description: Image type for the web server
    
    flavor:
        type: string
        description: Flavor for the web server

    subnet1:
        type: string
        description: subnet1

    subnet2:
        type: string
        description: subnet2

    http_security_group:
        type: string
        description: Nombre del grupo de seguridad por acceso a http

    postgres_security_group:
        type: string
        description: Nombre del grupo de seguridad por acceso a PostgreSQL

    icmp_security_group:
        type: string
        description: Nombre del grupo de seguridad por acceso a icmp

resources:
    vm-web:
        type: OS::Nova::Server
        properties:
            image: { get_param: image }
            flavor:  { get_param: flavor }
            networks:
                - subnet: { get_param: subnet1 }
                - subnet: { get_param: subnet2 }
            security_groups: 
                - { get_param: postgres_security_group }
                - { get_param: icmp_security_group }
                - { get_param: http_security_group }
