heat_template_version: 2017-02-24

parameters:
    image:
        type: string
        description: Image type for the web server
    
    flavor:
        type: string
        description: Flavor for the web server
    
    net2:
        type: string
        description: net2 identifier

    postgres_security_group:
        type: string
        description: PosrgreSQL security group

    icmp_security_group:
        type: string
        description: ICMP security group

    ssh_security_group:
        type: string
        description: SSH security group

resources:
    vm-postgres_net2_port:
        depends_on: [net2, icmp_security_group, postgres_security_group]
        type: OS::Neutron::Port
        properties:
            network_id: { get_resource: net2 }
            security_groups: 
                - { get_resource: postgres_security_group }
                - { get_resource: icmp_security_group }

    vm-postgres:
        depends_on: [vm-postgres_net2_port]
        type: OS::Nova::Server
        properties:
            image: { get_param: image }
            flavor:  { get_param: flavor }
            networks:
            - port: { get_resource: vm-postgres_net2_port }

outputs:
    OS::stack_id:
        value: { get_resource: vm-postgres }



