heat_template_version: 2017-02-24

description: Escenario de demonstracion completo, con ExtNet ya creada

parameters:
    ExtNet_name:
        type: string
        description: Nombre de la red externa

    net1_name:
        type: string
        description: Nombre de la red interna
    
    subnet1_name:
        type: string
        description: Nombre de la subred asociada a la red interna
    
    subnet1_gateway:
        type: string
        description: Gateway de la subred asociada a la red interna
        
    subnet1_dns:
        type: string
        description: Servidor DNS de la subred
        
    subnet1_cidr:
        type: string
        description: CIDR de la subred
        
    subnet1_start:
        type: string
        description: Start of the allocation pool 
        
    subnet1_end:
        type: string
        description: End of the allocation pool

    net2_name:
        type: string
        description: Nombre de la red de acceso a la base de datos
    
    subnet2_name:
        type: string
        description: Nombre de la subred asociada a la red de acceso a la base de datos
    
    subnet2_gateway:
        type: string
        description: Gateway de la subred asociada a la red de acceso a la base de datos
        
    subnet2_cidr:
        type: string
        description: CIDR de la subred asociada a la red de acceso a la base de datos
        
    subnet2_start:
        type: string
        description: Start of the allocation pool 
        
    subnet2_end:
        type: string
        description: End of the allocation pool
       
    r1_name:
        type: string
        description: Nombre del router

    ssh_security_group_name:
        type: string
        description: Nombre del grupo de seguridad por acceso a ssh

    http_security_group_name:
        type: string
        description: Nombre del grupo de seguridad por acceso a http

    postgres_security_group_name:
        type: string
        description: Nombre del grupo de seguridad por acceso a PostgreSQL

    icmp_security_group_name:
        type: string
        description: Nombre del grupo de seguridad por acceso a icmp
        
    vm-admin_image:
        type: string
        description: Tipo de imagen para vm-admin
        
    vm-admin_flavor:
        type: string
        description: Tipo de flavor para vm-admin

    vm-admin_key_name:
        type: string
        description: Nombre de la pareja de claves

    vm-postgres_image:
        type: string
        description: Tipo de imagen para la vm de la base de datos

    vm-postgres_flavor:
        type: string
        description: Tipo de flavor para la vm de la base de datos

    postgres_port:
        type: number
        description: Puerto de acceso a la base de datos

    min_web_server:
        type: number
        description: Numero minimo de servidores web

    max_web_server:
        type: number
        description: Numero maximo de servidores web

    vm-web_image:
        type: string
        description: Tipo de imagen para el servidor web
    
    vm-web_flavor:
        type: string
        description: Tipo de flavor para el servidor web

    web-group_scale_cooldown:
        type: number
        description: Cooldown para la escabilidad de los servidores web

    web_scale_avg_period:
        type: number
        description: Periodo para el calculo de la utilizacion de los servidores web

    web_scaleup_thresh:
        type: number
        description: Utilizacion minima para anadir un servidor web

    web_scaledown_thresh:
        type: number
        description: Utilizacion maxima para suprimir un servidor web 

    web_protocol_port:
        type: number
        description: Port number for web server 

    web_LBaaS_port:
        type: number
        description: Port number for LBaaS
  
        
resources:
    # TODO refactor net1 and net2, with only output beeing the subnet
    net1:
        type: OS::Neutron::ProviderNet
        properties:
            name: { get_param: net1_name }
            network_type: vlan
            
    subnet1:
        depends_on: [net1]
        type: OS::Neutron::Subnet 
        properties:
            name: { get_param: subnet1_name }
            network_id: { get_resource: net1 }
            gateway_ip: { get_param: subnet1_gateway }
            dns_nameservers: [{ get_param: subnet1_dns }]
            cidr: { get_param: subnet1_cidr }
            allocation_pools: 
                - { start: { get_param: subnet1_start }, end: { get_param: subnet1_end }}

    net2:
        type: OS::Neutron::ProviderNet
        properties:
            name: { get_param: net2_name }
            network_type: vlan
            
    subnet2:
        depends_on: [net2]
        type: OS::Neutron::Subnet 
        properties:
            name: { get_param: subnet2_name }
            network_id: { get_resource: net2 }
            gateway_ip: { get_param: subnet2_gateway }
            cidr: { get_param: subnet2_cidr }
            allocation_pools: 
                - { start: { get_param: subnet2_start }, end: { get_param: subnet2_end }}
            
    r1:
        type: OS::Neutron::Router
        properties:
            name: { get_param: r1_name }
            external_gateway_info:
                network: { get_param: ExtNet_name }
    
    r1_interface0:
        depends_on: [r1, subnet1]
        type: OS::Neutron::RouterInterface
        properties:
            router_id: { get_resource: r1 }
            subnet_id: { get_resource: subnet1}
            
    ssh_security_group:
        type: OS::Neutron::SecurityGroup 
        properties:
            name: { get_param: ssh_security_group_name }
            rules:
            -   remote_ip_prefix: 0.0.0.0/0 
                protocol: tcp 
                port_range_min: 22 
                port_range_max: 22

    http_security_group:
        type: OS::Neutron::SecurityGroup 
        properties:
            name: { get_param: http_security_group_name }
            rules:
            -   remote_ip_prefix: 0.0.0.0/0 
                protocol: tcp 
                port_range_min: 80 
                port_range_max: 80
            -   remote_ip_prefix: 0.0.0.0/0 
                protocol: tcp 
                port_range_min: 443 
                port_range_max: 443

    postgres_security_group:
        type: OS::Neutron::SecurityGroup 
        properties: 
            name: { get_param: http_security_group_name }
            rules:
            -   remote_ip_prefix: 0.0.0.0/0 
                protocol: tcp 
                port_range_min: { get_param: postgres_port } 
                port_range_max: { get_param: postgres_port }

    icmp_security_group:
        type: OS::Neutron::SecurityGroup 
        properties:
            name: { get_param: http_security_group_name }
            rules:
            -   remote_ip_prefix: 0.0.0.0/0 
                protocol: icmp
    
    vm-admin:
        type: CNVR::Server::Admin
        depends_on: [ssh_security_group, icmp_security_group, postgres_security_group, subnet1, subnet2]
        properties:
            image: { get_param: vm-admin_image }
            flavor: { get_param: vm-admin_flavor }
            key_name: { get_param: vm-admin_key_name }
            ExtNet: { get_param: ExtNet_name }
            net1: { get_resource: net1 }
            net2: { get_resource: net2 }
            postgres_security_group: { get_resource: postgres_security_group }
            ssh_security_group: { get_resource: ssh_security_group }
            icmp_security_group: { get_resource: icmp_security_group }
    
    vm-postgres:
        type: CNVR::Server::Postgres
        depends_on: [ssh_security_group, icmp_security_group, postgres_security_group, subnet2]
        properties:
            image: { get_param: vm-admin_image }
            flavor: { get_param: vm-admin_flavor }
            net2: { get_resource: net2 }
            postgres_security_group: { get_resource: postgres_security_group }
            ssh_security_group: { get_resource: ssh_security_group }
            icmp_security_group: { get_resource: icmp_security_group }

    LBaaS_web:
        type: CNVR::LBaaS
        depends_on: [ssh_security_group, icmp_security_group, postgres_security_group, subnet1, subnet2, vm-postgres]
        properties:
            vm-web_image: { get_param: vm-admin_image }
            vm-web_flavor: { get_param: vm-admin_flavor }
            ExtNet: { get_param: ExtNet_name }
            net1: { get_resource: net1 }
            net2: { get_resource: net2 }
            subnet1: { get_resource: subnet1 }
            postgres_security_group: { get_resource: postgres_security_group }
            ssh_security_group: { get_resource: ssh_security_group }
            icmp_security_group: { get_resource: icmp_security_group }
            http_security_group: { get_param: http_security_group }
            web_LBaas_port: { get_param: web_LBaaS_port }
            min_web_server: { get_param: min_web_server }
            max_web_server: { get_param: max_web_server }
            web-group_scale_cooldown: { get_param: web-group_scale_cooldown }
            web_protocol_port: { get_param: web_protocol_port }
            web_scale_avg_period: { get_param: web_scale_avg_period }
            web_scaleup_thresh: { get_param: web_scaleup_tresh }
            web_scaledown_thresh: { get_param: web_scaledown_thresh }
            vm-postgres: { get_resource: vm-postgres }
            postgres_port: { get_param: postgres_port }
            
outputs:
    vm-admin_ip:
        description: Direccion IP asignada a vm-admin
        value: { get_attr: [vm-admin, first_address] }
        
    vm-admin_private_key:
        description: Clave privada de vm-admin
        value: { get_attr: [vm-admin, private_key] }

    LBaaS_ip:
        description: URL to reach the LBaaS
        value: { get_attr: [ LBaaS_web, ip ] }

    web-group_scaleup_url:
        description: URL para aumentar el numero de servidores web
        value: { get_attr: [web-group_scaleup_policy, signal_url]}

    web-group_scaledown_url:
        description: URL para aumentar el numero de servidores web
        value: { get_attr: [web-group_scaledown_policy, signal_url]}

